### ISSUE TITLE
PHP Enums not converted correctly

### ISSUE THREAD

**Issue by angauber** [spatie/typescript-transformer#18]
PHP Enums and backed Enums are not correctly converted to TS Enums

#14 introduced TS enums transformations but the [toEnum](https://github.com/spatie/typescript-transformer/blob/main/src/Transformers/EnumTransformer.php#L37) method always create [string enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums)

Is this the intended way ?

**Comment by rubenvanassche** [comment]
Hi @angauber,

You're right, enums shouldn't always be transformed into String enums. At the moment we're not using the enum functionality of the package (we just use a list of string, the default option) so I have no time at the moment to fix this. But I would accept a tested PR that adds this functionality!

**Comment by rovansteen** [comment]
I think #19 should resolve this issue.

**Comment by rubenvanassche** [comment]
Merged and released!
