### ISSUE TITLE
Spatie Enum transformer is in no way related to Laravel

### ISSUE THREAD

**Issue by Gummibeer** [spatie/typescript-transformer#4]
The `spatie/enum` package itself and the corresponding transformer are in no way related to Laravel. So the [SpatieEnumTransformer](https://github.com/spatie/laravel-typescript-transformer/blob/master/src/Transformers/SpatieEnumTransformer.php) could be moved into this base package to provide this functionality more users.

**Comment by rubenvanassche** [comment]
Hi Tom,

Good point, moved the class and tagged for both packages 1.1.0!
