### ISSUE TITLE
i am using this packge but unable to transform the php class into typeScript

### ISSUE THREAD

**Issue by atif08** [spatie/typescript-transformer#52]
My Php Class

<?php

namespace Domain\Orders\DataTransferObjects;

use Spatie\TypeScriptTransformer\Attributes\TypeScript;

#[TypeScript]
class TestType
{
    public string $name;

}

and i get this response in my console

+-----------+-------------------+
| PHP class | TypeScript entity |
+-----------+-------------------+
Transformed 0 PHP types to TypeScript

**Comment by freekmurze** [comment]
Too little info
