### ISSUE TITLE
Mechanism to include multiple search paths?

### ISSUE THREAD

**Issue by timmartin19** [spatie/typescript-transformer#8]
I was wondering if there was a mechanism to include multiple search paths?  We're looking to introduce to a fairly large code base and it can take a long time to search through all the classes.  However, we have classes in a couple different top level directories that we'd like to convert.  

```
app/
  Foo/
  Bar/
  Irrelevant/
```

Something like `search_paths' => [app_path('Foo'), app_path('Bar')]` would be awesome but I'm not sure how to go about it.

**Comment by rubenvanassche** [comment]
Hi @timmartin19,

That's a good point, I'm currently working on v2, let me take a look how easy it is to add multiple search paths.

**Comment by rubenvanassche** [comment]
Hi @timmartin19 this is now a new feature in v2!
